### PR TITLE
Add helpful messages, we have linux users too!

### LINKED ISSUE #1: `x not found` errors suggest Mac commands on Linux
If various components are not installed, the suggested commands [are all `brew install foo`](https://github.com/maelvls/ngroker/blob/master/ngroker#L73-L95) no matter what OS the user is on.

As a Linux user I am deeply offended by this!

😜

### PR DESCRIPTION
**Pull request by maelvls**
Closes #1

### CODE REVIEW

**Comment by maelvls** [comment]
What do you think @Callisto13? 😄

**Comment by Callisto13** [comment]
Hmmmm could do with a refactor, but I'll allow it 😉

**Comment by maelvls** [comment]
I'm so lazy lol

**Comment by maelvls** [comment]
one day I'll make that all pretty and shiny

**Pull request merged**
